// 22 Official Eighth Schedule Languages of India + English
// Provides localized names, scripts, speech recognition/synthesis BCP 47 language codes,
// and core UI translation strings for dual-role caregiver and patient views.

const INDIAN_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', script: 'Latin', bcp47: 'en-IN', region: 'Pan-India' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', script: 'Devanagari', bcp47: 'hi-IN', region: 'North / Central India' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া', script: 'Bengali-Assamese', bcp47: 'as-IN', region: 'Assam' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', script: 'Bengali', bcp47: 'bn-IN', region: 'West Bengal / Tripura' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', script: 'Gujarati', bcp47: 'gu-IN', region: 'Gujarat' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', script: 'Kannada', bcp47: 'kn-IN', region: 'Karnataka' },
  { code: 'ks', name: 'Kashmiri', native: 'کٲشُر / कश्मीरी', script: 'Perso-Arabic / Devanagari', bcp47: 'ks-IN', region: 'Jammu & Kashmir' },
  { code: 'kok', name: 'Konkani', native: 'कोंकणी', script: 'Devanagari', bcp47: 'kok-IN', region: 'Goa / Coastal Maharashtra' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', script: 'Malayalam', bcp47: 'ml-IN', region: 'Kerala' },
  { code: 'mni', name: 'Manipuri (Meitei)', native: 'মৈতৈলোন্ / ꯃꯩꯇꯩꯂꯣꯟ', script: 'Bengali / Meetei Mayek', bcp47: 'mni-IN', region: 'Manipur' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', script: 'Devanagari', bcp47: 'mr-IN', region: 'Maharashtra' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली', script: 'Devanagari', bcp47: 'ne-NP', region: 'Sikkim / North Bengal' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ', script: 'Odia', bcp47: 'or-IN', region: 'Odisha' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', script: 'Gurmukhi', bcp47: 'pa-IN', region: 'Punjab' },
  { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्', script: 'Devanagari', bcp47: 'sa-IN', region: 'Pan-India Classical' },
  { code: 'sat', name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ', script: 'Ol Chiki', bcp47: 'sat-IN', region: 'Jharkhand / Odisha / WB' },
  { code: 'sd', name: 'Sindhi', native: 'سنڌي / सिन्धी', script: 'Perso-Arabic / Devanagari', bcp47: 'sd-IN', region: 'Sindhi Diaspora' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', script: 'Tamil', bcp47: 'ta-IN', region: 'Tamil Nadu / Puducherry' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', script: 'Telugu', bcp47: 'te-IN', region: 'Andhra Pradesh / Telangana' },
  { code: 'ur', name: 'Urdu', native: 'اردو', script: 'Perso-Arabic', bcp47: 'ur-IN', region: 'Pan-India' },
  { code: 'brx', name: 'Bodo', native: 'बड़ो', script: 'Devanagari', bcp47: 'brx-IN', region: 'Bodoland (Assam)' },
  { code: 'doi', name: 'Dogri', native: 'डोगरी', script: 'Devanagari', bcp47: 'doi-IN', region: 'Jammu & Kashmir' },
  { code: 'mai', name: 'Maithili', native: 'मैथिली', script: 'Devanagari', bcp47: 'mai-IN', region: 'Bihar / Jharkhand' }
];

// Core UI translation keys for all languages
const TRANSLATIONS = {
  en: {
    home: "Home",
    games: "Games",
    family: "Family",
    meds: "Meds",
    voiceAi: "Voice AI",
    currentTime: "CURRENT TIME",
    morningMeds: "Morning Meds",
    gamePlayed: "1 Game Played",
    eveningDose: "Evening Dose 8PM",
    askAssistant: "Need anything? Just Ask.",
    tapToSpeak: "Tap here to speak or ask when your next medicine is due.",
    brainGames: "Brain Games",
    playExercise: "Play today's exercise",
    familyCalling: "Family Calling",
    tapToCall: "Tap photo to call",
    medication: "Medication",
    viewRx: "View prescription card",
    familyPhotos: "Family Photos",
    browseMemories: "Browse memories",
    emergencyCall: "Direct 1-tap call to Priya Sharma",
    callNow: "Call Now",
    voiceWelcome: "Listening... speak comfortably in your own language.",
    voicePlaceholder: "Ask about medicines, family calls, or games...",
    overview: "Overview",
    caregiverPortal: "Caregiver Dashboard",
    patientMode: "Patient View",
    lightMode: "Light Mode",
    darkMode: "Dark Mode"
  },
  hi: {
    home: "होम",
    games: "खेल",
    family: "परिवार",
    meds: "दवाई",
    voiceAi: "आवाज़ AI",
    currentTime: "वर्तमान समय",
    morningMeds: "सुबह की दवाई",
    gamePlayed: "१ खेल पूरा हुआ",
    eveningDose: "शाम की खुराक रात 8 बजे",
    askAssistant: "कुछ चाहिए? बस बोलिए।",
    tapToSpeak: "बोलने के लिए यहाँ टैप करें या दवाई का समय पूछें।",
    brainGames: "दिमागी खेल",
    playExercise: "आज का अभ्यास खेलें",
    familyCalling: "परिवार को कॉल",
    tapToCall: "कॉल करने के लिए फोटो छूएं",
    medication: "दवाइयाँ",
    viewRx: "दवाई का पर्चा देखें",
    familyPhotos: "पारिवारिक तस्वीरें",
    browseMemories: "यादें देखें",
    emergencyCall: "प्रिया शर्मा को सीधा १-टैप कॉल",
    callNow: "अभी कॉल करें",
    voiceWelcome: "सुन रहा हूँ... अपनी भाषा में आराम से बोलें।",
    voicePlaceholder: "दवाई, परिवार को कॉल या खेल के बारे में पूछें...",
    overview: "अवलोकन",
    caregiverPortal: "केयरगिवर डैशबोर्ड",
    patientMode: "मरीज़ दृश्य",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड"
  },
  bn: {
    home: "হোম",
    games: "খেলাধুলা",
    family: "পরিবার",
    meds: "ওষুধ",
    voiceAi: "ভয়েস AI",
    currentTime: "বর্তমান সময়",
    morningMeds: "সকালের ওষুধ",
    gamePlayed: "১টি খেলা সম্পন্ন",
    eveningDose: "সন্ধ্যার ডোজ রাত ৮টায়",
    askAssistant: "কিছু দরকার? শুধু বলুন।",
    tapToSpeak: "কথা বলতে এখানে ট্যাপ করুন বা ওষুধের সময় জানুন।",
    brainGames: "মস্তিষ্কের খেলা",
    playExercise: "আজকের ব্যায়াম খেলুন",
    familyCalling: "পরিবারকে কল",
    tapToCall: "কল করতে ছবিতে স্পর্শ করুন",
    medication: "ওষুধপত্র",
    viewRx: "প্রেসক্রিপশন দেখুন",
    familyPhotos: "পারিবারিক ছবি",
    browseMemories: "স্মৃতিগুলো দেখুন",
    emergencyCall: "প্রিয়া শর্মাকে সরাসরি ১-ট্যাপ কল",
    callNow: "এখনই কল করুন",
    voiceWelcome: "শুনছি... আপনার ভাষায় স্বাচ্ছন্দ্যে বলুন।",
    voicePlaceholder: "ওষুধ, পরিবারের কল বা খেলা সম্পর্কে জিজ্ঞাসা করুন...",
    overview: "ওভারভিউ",
    caregiverPortal: "কেয়ারগিভার ড্যাশবোর্ড",
    patientMode: "রোগী ভিউ",
    lightMode: "লাইট মোড",
    darkMode: "ডার্ক মোড"
  },
  te: {
    home: "హోమ్",
    games: "ఆటలు",
    family: "కుటుంబం",
    meds: "మందులు",
    voiceAi: "వాయిస్ AI",
    currentTime: "ప్రస్తుత సమయం",
    morningMeds: "ఉదయం మందులు",
    gamePlayed: "1 గేమ్ ఆడారు",
    eveningDose: "రాత్రి 8 గంటలకు మోతాదు",
    askAssistant: "ఏమైనా కావాలా? అడగండి.",
    tapToSpeak: "మాట్లాడటానికి ఇక్కడ నొక్కండి లేదా మందుల సమయం అడగండి.",
    brainGames: "మెదడు ఆటలు",
    playExercise: "నేటి వ్యాయామం ఆడండి",
    familyCalling: "కుటుంబానికి కాల్",
    tapToCall: "కాల్ చేయడానికి ఫోటో తాకండి",
    medication: "మందులు",
    viewRx: "ప్రిస్క్రిప్షన్ చూడండి",
    familyPhotos: "కుటుంబ ఫోటోలు",
    browseMemories: "జ్ఞాపకాలను చూడండి",
    emergencyCall: "ప్రియా శర్మకు 1-ట్యాప్ కాల్",
    callNow: "ఇప్పుడే కాల్ చేయండి",
    voiceWelcome: "వింటున్నాను... మీ భాషలో మాట్లాడండి.",
    voicePlaceholder: "మందులు, కాల్స్ లేదా ఆటల గురించి అడగండి...",
    overview: "సమీక్ష",
    caregiverPortal: "సంరక్షకుని డాష్‌బోర్డ్",
    patientMode: "రోగి వీక్షణ",
    lightMode: "లైట్ మోడ్",
    darkMode: "డార్క్ మోడ్"
  },
  ta: {
    home: "முகப்பு",
    games: "விளையாட்டுகள்",
    family: "குடும்பம்",
    meds: "மருந்துகள்",
    voiceAi: "குரல் AI",
    currentTime: "தற்போதைய நேரம்",
    morningMeds: "காலை மருந்துகள்",
    gamePlayed: "1 விளையாட்டு முடிந்தது",
    eveningDose: "இரவு 8 மணி மருந்தளவு",
    askAssistant: "ஏதேனும் தேவையா? கேளுங்கள்.",
    tapToSpeak: "பேச இங்கு தட்டவும் அல்லது மருந்து நேரத்தைக் கேட்கவும்.",
    brainGames: "மூளை விளையாட்டுகள்",
    playExercise: "இன்றைய பயிற்சியை விளையாடுங்கள்",
    familyCalling: "குடும்பத்திற்கு அழைப்பு",
    tapToCall: "அழைக்க புகைப்படத்தைத் தொடவும்",
    medication: "மருந்துகள்",
    viewRx: "மருந்துச் சீட்டைப் பார்க்கவும்",
    familyPhotos: "குடும்பப் படங்கள்",
    browseMemories: "நினைவுகளைப் பார்க்கவும்",
    emergencyCall: "பிரியா சர்மாவுக்கு உடனடி அழைப்பு",
    callNow: "இப்போதே அழைக்கவும்",
    voiceWelcome: "கேட்கிறேன்... உங்கள் மொழியில் வசதியாகப் பேசுங்கள்.",
    voicePlaceholder: "மருந்து, குடும்ப அழைப்பு அல்லது விளையாட்டு பற்றிக் கேளுங்கள்...",
    overview: "கண்ணோட்டம்",
    caregiverPortal: "பராமரிப்பாளர் பலகை",
    patientMode: "நோயாளி பார்வை",
    lightMode: "ஒளி பயன்முறை",
    darkMode: "இருள் பயன்முறை"
  },
  mr: {
    home: "मुख्यपृष्ठ",
    games: "खेळ",
    family: "कुटुंब",
    meds: "औषधे",
    voiceAi: "व्हॉइस AI",
    currentTime: "सध्याची वेळ",
    morningMeds: "सकाळची औषधे",
    gamePlayed: "१ खेळ खेळला",
    eveningDose: "रात्री ८ वाजताचा डोस",
    askAssistant: "काही मदत हवी आहे? विचारा.",
    tapToSpeak: "बोलण्यासाठी येथे टॅप करा किंवा औषधांची वेळ विचारा.",
    brainGames: "मेंदूचे खेळ",
    playExercise: "आजचा सराव खेळा",
    familyCalling: "कुटुंबाला कॉल",
    tapToCall: "कॉल करण्यासाठी फोटोला स्पर्श करा",
    medication: "औषधे",
    viewRx: "प्रिस्क्रिप्शन कार्ड पहा",
    familyPhotos: "कौटुंबिक फोटो",
    browseMemories: "आठवणी पहा",
    emergencyCall: "प्रिया शर्मा यांना थेट कॉल",
    callNow: "आता कॉल करा",
    voiceWelcome: "ऐकत आहे... आपल्या भाषेत बोला.",
    voicePlaceholder: "औषधे, कॉल किंवा खेळांबद्दल विचारा...",
    overview: "आढावा",
    caregiverPortal: "केअरगिव्हर डॅशबोर्ड",
    patientMode: "रुग्ण दृश्य",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड"
  },
  gu: {
    home: "હોમ",
    games: "રમતો",
    family: "પરિવાર",
    meds: "દવાઓ",
    voiceAi: "વૉઇસ AI",
    currentTime: "હાલનો સમય",
    morningMeds: "સવારની દવાઓ",
    gamePlayed: "૧ રમત રમી",
    eveningDose: "સાંજે ૮ વાગ્યે ડોઝ",
    askAssistant: "કંઈક જોઈએ છે? પૂછો.",
    tapToSpeak: "બોલવા માટે અહીં ટેપ કરો અથવા દવાનો સમય પૂછો.",
    brainGames: "મગજની રમતો",
    playExercise: "આજની કસરત રમો",
    familyCalling: "પરિવારને કૉલ",
    tapToCall: "કૉલ કરવા માટે ફોટો ટચ કરો",
    medication: "દવાઓ",
    viewRx: "દવાનું પ્રિસ્ક્રિપ્શન જુઓ",
    familyPhotos: "પરિવારના ફોટા",
    browseMemories: "યાદો જુઓ",
    emergencyCall: "પ્રિયા શર્માને સીધો ૧-ટેપ કૉલ",
    callNow: "હમણાં કૉલ કરો",
    voiceWelcome: "સાંભળી રહ્યો છું... તમારી ભાષામાં બોલો.",
    voicePlaceholder: "દવા, કૉલ અથવા રમતો વિશે પૂછો...",
    overview: "ઝાંખી",
    caregiverPortal: "કેરગિવર ડેશબોર્ડ",
    patientMode: "દર્દી દૃશ્ય",
    lightMode: "લાઇટ મોડ",
    darkMode: "ડાર્ક મોડ"
  },
  kn: {
    home: "ಮುಖಪುಟ",
    games: "ಆಟಗಳು",
    family: "ಕುಟುಂಬ",
    meds: "ಔಷಧಿಗಳು",
    voiceAi: "ಧ್ವನಿ AI",
    currentTime: "ಪ್ರಸ್ತುತ ಸಮಯ",
    morningMeds: "ಬೆಳಗಿನ ಔಷಧಿ",
    gamePlayed: "1 ಆಟ ಮುಗಿದಿದೆ",
    eveningDose: "ರಾತ್ರಿ 8 ಗಂಟೆಯ ಡೋಸ್",
    askAssistant: "ಏನಾದರೂ ಬೇಕೇ? ಕೇಳಿ.",
    tapToSpeak: "ಮಾತನಾಡಲು ಇಲ್ಲಿ ಟ್ಯಾಪ್ ಮಾಡಿ ಅಥವಾ ಔಷಧಿಯ ಸಮಯ ಕೇಳಿ.",
    brainGames: "ಮೆದುಳಿನ ಆಟಗಳು",
    playExercise: "ಇಂದಿನ ಆಟವನ್ನು ಆಡಿ",
    familyCalling: "ಕುಟುಂಬಕ್ಕೆ ಕರೆ",
    tapToCall: "ಕರೆ ಮಾಡಲು ಫೋಟೋ ಸ್ಪರ್ಶಿಸಿ",
    medication: "ಔಷಧಿಗಳು",
    viewRx: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ವೀಕ್ಷಿಸಿ",
    familyPhotos: "ಕುಟುಂಬದ ಫೋಟೋಗಳು",
    browseMemories: "ನೆನಪುಗಳನ್ನು ನೋಡಿ",
    emergencyCall: "ಪ್ರಿಯಾ ಶರ್ಮಾ ಅವರಿಗೆ ನೇರ ಕರೆ",
    callNow: "ಈಗಲೇ ಕರೆ ಮಾಡಿ",
    voiceWelcome: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ... ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ.",
    voicePlaceholder: "ಔಷಧಿ, ಕರೆ ಅಥವಾ ಆಟಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    overview: "ಅವಲೋಕನ",
    caregiverPortal: "ಆರೈಕೆದಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    patientMode: "ರೋಗಿಯ ನೋಟ",
    lightMode: "ಬೆಳಕಿನ ಮೋಡ್",
    darkMode: "ಕತ್ತಲೆಯ ಮೋಡ್"
  },
  ml: {
    home: "ഹോം",
    games: "കളികൾ",
    family: "കുടുംബം",
    meds: "മരുന്നുകൾ",
    voiceAi: "വോയ്‌സ് AI",
    currentTime: "ഇപ്പോഴത്തെ സമയം",
    morningMeds: "രാവിലത്തെ മരുന്ന്",
    gamePlayed: "1 കളി കളിച്ചു",
    eveningDose: "രാത്രി 8 മണിക്ക് മരുന്ന്",
    askAssistant: "എന്തെങ്കിലും വേണോ? ചോദിക്കൂ.",
    tapToSpeak: "സംസാരിക്കാൻ ഇവിടെ ടാപ്പ് ചെയ്യുക.",
    brainGames: "ബുദ്ധി വികാസ കളികൾ",
    playExercise: "ഇന്നത്തെ കളി ആരംഭിക്കുക",
    familyCalling: "കുടുംബത്തെ വിളിക്കുക",
    tapToCall: "വിളിക്കാൻ ഫോട്ടോയിൽ തൊടുക",
    medication: "മരുന്നുകൾ",
    viewRx: "കുറിപ്പടി കാണുക",
    familyPhotos: "കുടുംബ ചിത്രങ്ങൾ",
    browseMemories: "ഓർമ്മകൾ കാണുക",
    emergencyCall: "പ്രിയ ശർമ്മയ്ക്ക് നേരിട്ടുള്ള കോൾ",
    callNow: "ഇപ്പോൾ വിളിക്കുക",
    voiceWelcome: "കേൾക്കുന്നു... നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കൂ.",
    voicePlaceholder: "മരുന്ന്, കോൾ, കളി എന്നിവയെക്കുറിച്ച് ചോദിക്കൂ...",
    overview: "അവലോകനം",
    caregiverPortal: "കെയർഗിവർ ഡാഷ്‌ബോർഡ്",
    patientMode: "രോഗി കാഴ്ച",
    lightMode: "ലൈറ്റ് മോഡ്",
    darkMode: "ഡാർക്ക് മോഡ്"
  },
  as: {
    home: "ঘৰ",
    games: "খেল",
    family: "পৰিয়াল",
    meds: "ঔষধ",
    voiceAi: "ভইচ AI",
    currentTime: "বৰ্তমান সময়",
    morningMeds: "ৰাতিপুৱাৰ ঔষধ",
    gamePlayed: "১টা খেল সমাপ্ত",
    eveningDose: "নিশা ৮ বজাৰ ঔষধ",
    askAssistant: "কিবা লাগিব নেকি? মাত্ৰ কওক।",
    tapToSpeak: "কথা ক'বলৈ ইয়াত টিপক।",
    brainGames: "মগজুৰ খেল",
    playExercise: "আজিৰ অনুশীলন খেলক",
    familyCalling: "পৰিয়ালক কল",
    tapToCall: "কল কৰিবলৈ ফটো স্পৰ্শ কৰক",
    medication: "ঔষধসমূহ",
    viewRx: "প্ৰেচক্ৰিপশ্বন চাওক",
    familyPhotos: "পৰিয়ালৰ ছবি",
    browseMemories: "স্মৃতিসমূহ চাওক",
    emergencyCall: "প্ৰিয়া শৰ্মালৈ পোনপটীয়া কল",
    callNow: "এতিয়াই কল কৰক",
    voiceWelcome: "শুনি আছো... আপোনাৰ ভাষাত কওক।",
    voicePlaceholder: "ঔষধ, কল বা খেলৰ বিষয়ে সোধক...",
    overview: "অৱলোকন",
    caregiverPortal: "কেয়াৰগিভাৰ ডেচবৰ্ড",
    patientMode: "ৰোগী দৃশ্য",
    lightMode: "লাইট ম'ড",
    darkMode: "ডাৰ্ক ম'ড"
  },
  pa: {
    home: "ਮੁੱਖ ਪੰਨਾ",
    games: "ਖੇਡਾਂ",
    family: "ਪਰਿਵਾਰ",
    meds: "ਦਵਾਈਆਂ",
    voiceAi: "ਆਵਾਜ਼ AI",
    currentTime: "ਮੌਜੂਦਾ ਸਮਾਂ",
    morningMeds: "ਸਵੇਰ ਦੀ ਦਵਾਈ",
    gamePlayed: "1 ਖੇਡ ਮੁਕੰਮਲ",
    eveningDose: "ਰਾਤ 8 ਵਜੇ ਦੀ ਖੁਰਾਕ",
    askAssistant: "ਕੁਝ ਚਾਹੀਦਾ ਹੈ? ਪੁੱਛੋ।",
    tapToSpeak: "ਬੋਲਣ ਲਈ ਇੱਥੇ ਟੈਪ ਕਰੋ।",
    brainGames: "ਦਿਮਾਗੀ ਖੇਡਾਂ",
    playExercise: "ਅੱਜ ਦਾ ਅਭਿਆਸ ਖੇਡੋ",
    familyCalling: "ਪਰਿਵਾਰ ਨੂੰ ਕਾਲ",
    tapToCall: "ਕਾਲ ਕਰਨ ਲਈ ਫ਼ੋਟੋ ਛੂਹੋ",
    medication: "ਦਵਾਈਆਂ",
    viewRx: "ਪਰਚੀ ਦੇਖੋ",
    familyPhotos: "ਪਰਿਵਾਰਕ ਤਸਵੀਰਾਂ",
    browseMemories: "ਯਾਦਾਂ ਦੇਖੋ",
    emergencyCall: "ਪ੍ਰਿਆ ਸ਼ਰਮਾ ਨੂੰ ਸਿੱਧੀ ਕਾਲ",
    callNow: "ਹੁਣੇ ਕਾਲ ਕਰੋ",
    voiceWelcome: "ਸੁਣ ਰਿਹਾ ਹਾਂ... ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ।",
    voicePlaceholder: "ਦਵਾਈ, ਕਾਲ ਜਾਂ ਖੇਡ ਬਾਰੇ ਪੁੱਛੋ...",
    overview: "ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
    caregiverPortal: "ਦੇਖਭਾਲਕਰਤਾ ਡੈਸ਼ਬੋਰਡ",
    patientMode: "ਮਰੀਜ਼ ਦ੍ਰਿਸ਼",
    lightMode: "ਲਾਈਟ ਮੋਡ",
    darkMode: "ਡਾਰਕ ਮੋਡ"
  },
  or: {
    home: "ମୁଖ୍ୟପୃଷ୍ଠା",
    games: "ଖେଳ",
    family: "ପରିବାର",
    meds: "ଔଷଧ",
    voiceAi: "ଭଏସ୍ AI",
    currentTime: "ବର୍ତ୍ତମାନ ସମୟ",
    morningMeds: "ସକାଳ ଔଷଧ",
    gamePlayed: "୧ ଖେଳ ସମ୍ପନ୍ନ",
    eveningDose: "ରାତି ୮ଟା ଔଷଧ",
    askAssistant: "କିଛି ଆବଶ୍ୟକ କି? ପଚାରନ୍ତୁ।",
    tapToSpeak: "କହିବା ପାଇଁ ଏଠାରେ ଟ୍ୟାପ୍ କରନ୍ତୁ।",
    brainGames: "ମସ୍ତିଷ୍କ ଖେଳ",
    playExercise: "ଆଜିର ଅଭ୍ୟାସ ଖେଳନ୍ତୁ",
    familyCalling: "ପରିବାରକୁ କଲ୍",
    tapToCall: "କଲ୍ କରିବାକୁ ଫଟୋ ଛୁଅନ୍ତୁ",
    medication: "ଔଷଧ",
    viewRx: "ପ୍ରେସକ୍ରିପସନ୍ ଦେଖନ୍ତୁ",
    familyPhotos: "ପାରିବାରିକ ଫଟୋ",
    browseMemories: "ସ୍ମୃତି ଦେଖନ୍ତୁ",
    emergencyCall: "ପ୍ରିୟା ଶର୍ମାଙ୍କୁ ସିଧାସଳଖ କଲ୍",
    callNow: "ଏବେ କଲ୍ କରନ୍ତୁ",
    voiceWelcome: "ଶୁଣୁଛି... ଆପଣଙ୍କ ଭାଷାରେ କୁହନ୍ତୁ।",
    voicePlaceholder: "ଔଷଧ, କଲ୍ କିମ୍ବା ଖେଳ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    overview: "ସମୀକ୍ଷା",
    caregiverPortal: "କେୟାରଗିଭର ଡ୍ୟାସବୋର୍ଡ",
    patientMode: "ରୋଗୀ ଦୃଶ୍ୟ",
    lightMode: "ଲାଇଟ୍ ମୋଡ୍",
    darkMode: "ଡାର୍କ ମୋଡ୍"
  },
  ur: {
    home: "ہوم",
    games: "کھیل",
    family: "خاندان",
    meds: "دوائیں",
    voiceAi: "وائس AI",
    currentTime: "موجودہ وقت",
    morningMeds: "صبح کی دوائیں",
    gamePlayed: "1 کھیل مکمل",
    eveningDose: "رات 8 بجے کی خوراک",
    askAssistant: "کچھ چاہیے؟ بس فرمائیے۔",
    tapToSpeak: "بولنے کے لیے یہاں ٹیپ کریں۔",
    brainGames: "دماغی کھیل",
    playExercise: "آج کی مشق کھیلیں",
    familyCalling: "اہل خانہ کو کال",
    tapToCall: "کال کرنے کے لیے تصویر چھوئیں",
    medication: "دوائیں",
    viewRx: "نسخہ دیکھیں",
    familyPhotos: "خاندانی تصاویر",
    browseMemories: "یادیں دیکھیں",
    emergencyCall: "پریا شرما کو فوری کال",
    callNow: "ابھی کال کریں",
    voiceWelcome: "سن رہا ہوں... اپنی زبان میں بات کریں۔",
    voicePlaceholder: "دوا، کال یا کھیل کے بارے میں پوچھیں...",
    overview: "جائزہ",
    caregiverPortal: "کیئرگیور ڈیش بورڈ",
    patientMode: "مریض منظر",
    lightMode: "لائٹ موڈ",
    darkMode: "ڈارک موڈ"
  }
};

// Fallback helper to populate remaining regional languages smoothly
INDIAN_LANGUAGES.forEach(lang => {
  if (!TRANSLATIONS[lang.code]) {
    TRANSLATIONS[lang.code] = {
      ...TRANSLATIONS.hi,
      home: `${lang.native} Home`,
      voiceWelcome: `CareLoop (${lang.name}) - ${lang.native}`,
      voicePlaceholder: `Ask in ${lang.name} (${lang.native})...`
    };
  }
});

module.exports = {
  INDIAN_LANGUAGES,
  TRANSLATIONS
};
